# Base Image
FROM python:3.11-slim

WORKDIR /app

# Install System Dep
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Install Python Dep
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Code
COPY . .

# Run Server
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]