"""
Next.js (App Router) frontend generator for Agent 50.
"""

import json
from pathlib import Path
from typing import Dict, Any
import logging

class NextJSGenerator:
    """Generates Next.js 14+ (App Router) frontend."""
    
    def __init__(self):
        self.logger = logging.getLogger("Agent50.Builder.NextJS")
    
    def generate(self, blueprint: Dict[str, Any], output_path: Path):
        """Generate Next.js project structure."""
        self.logger.info(f"Generating Next.js frontend at: {output_path}")
        
        # Structure
        app_path = output_path / "app"
        app_path.mkdir(parents=True, exist_ok=True)
        (output_path / "components" / "ui").mkdir(parents=True, exist_ok=True)
        (output_path / "lib").mkdir(exist_ok=True)
        (output_path / "public").mkdir(exist_ok=True)
        
        # Configs
        self._generate_configs(output_path)
        
        # App Directory
        self._generate_app_structure(blueprint, app_path)
        
        # Libs
        self._generate_libs(output_path / "lib")
        
        self.logger.info("Next.js frontend generation complete")

    def _generate_configs(self, output_path: Path):
        """Generate config files."""
        
        # next.config.js
        (output_path / "next.config.js").write_text("""/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: ['ui-avatars.com'],
  },
  async rewrites() {
    return [
      {
        source: '/api/:path*',
        destination: 'http://localhost:8000/api/v1/:path*',
      },
    ]
  },
}

module.exports = nextConfig
""")

        # tsconfig.json
        (output_path / "tsconfig.json").write_text("""{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
""")

        # tailwind.config.ts
        (output_path / "tailwind.config.ts").write_text("""import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#3b82f6',
      },
    },
  },
  plugins: [],
}
export default config
""")

        # next-env.d.ts
        (output_path / "next-env.d.ts").write_text("""/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
""")

    def _generate_app_structure(self, blueprint: Dict[str, Any], app_path: Path):
        """Generate app/ directory files."""
        
        # globals.css
        (app_path / "globals.css").write_text("""@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: white;
}
""")

        # layout.tsx
        (app_path / "layout.tsx").write_text(f"""import type {{ Metadata }} from 'next'
import {{ Inter }} from 'next/font/google'
import './globals.css'

const inter = Inter({{ subsets: ['latin'] }})

export const metadata: Metadata = {{
  title: '{blueprint.get('name', 'Next App')}',
  description: '{blueprint.get('description', 'Generated by Agent 50')}',
}}

export default function RootLayout({{
  children,
}}: {{
  children: React.ReactNode
}}) {{
  return (
    <html lang="en">
      <body className={{inter.className}}>
        <nav className="border-b h-16 flex items-center px-8 justify-between bg-white">
            <div className="font-bold text-xl">{blueprint.get('name', 'App')}</div>
            <div className="flex gap-4">
                <a href="/" className="hover:underline">Home</a>
                <a href="/dashboard" className="hover:underline">Dashboard</a>
            </div>
        </nav>
        <main className="min-h-[calc(100vh-64px)] bg-gray-50">
            {{children}}
        </main>
      </body>
    </html>
  )
}}
""")

        # page.tsx
        (app_path / "page.tsx").write_text("""export default function Home() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-6xl font-bold mb-8 text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">
        Next.js App
      </h1>
      <p className="text-xl text-gray-600 mb-8 text-center max-w-2xl">
        This full-stack application was generated by Agent 50. It uses Next.js App Router, Tailwind CSS, and connects to a Python backend.
      </p>
      
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 w-full max-w-4xl">
        <div className="p-6 bg-white rounded-xl shadow-sm border hover:shadow-md transition">
          <h2 className="text-2xl font-semibold mb-2">Server Components</h2>
          <p className="text-gray-600">React Server Components for optimal performance and SEO.</p>
        </div>
        <div className="p-6 bg-white rounded-xl shadow-sm border hover:shadow-md transition">
          <h2 className="text-2xl font-semibold mb-2">API Integration</h2>
          <p className="text-gray-600">Pre-configured proxy to connect seamlessly with FastAPI/Django/Flask.</p>
        </div>
        <div className="p-6 bg-white rounded-xl shadow-sm border hover:shadow-md transition">
          <h2 className="text-2xl font-semibold mb-2">Modern UI</h2>
          <p className="text-gray-600">Styled with Tailwind CSS for rapid UI development.</p>
        </div>
      </div>
    </div>
  )
}
""")

        # dashboard/page.tsx
        (app_path / "dashboard").mkdir(exist_ok=True)
        (app_path / "dashboard" / "page.tsx").write_text("""import { getData } from '@/lib/api'

export default async function Dashboard() {
  // Example of Server Component Data Fetching
  // const data = await getData('/dashboard/stats') 
  
  return (
    <div className="p-8">
      <h1 className="text-3xl font-bold mb-6">Dashboard</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {[1, 2, 3, 4].map((i) => (
            <div key={i} className="bg-white p-6 rounded-xl shadow-sm border">
                <div className="text-gray-500 text-sm">Metric {i}</div>
                <div className="text-3xl font-bold mt-2">{Math.floor(Math.random() * 1000)}</div>
            </div>
        ))}
      </div>
    </div>
  )
}
""")

    def _generate_libs(self, lib_path: Path):
        """Generate utility libraries."""
        
        # api.ts
        (lib_path / "api.ts").write_text("""const BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api/v1';

export async function getData(endpoint: string) {
  const res = await fetch(`${BASE_URL}${endpoint}`, { cache: 'no-store' });
  
  if (!res.ok) {
    throw new Error('Failed to fetch data');
  }
 
  return res.json();
}
""")