"""
memory_manager.py - The Brain of Agent 50.
Standard: DEEPSEEK SUPREME LEVEL.
Features: Full Pattern Recognition + Dashboard Compatibility + Auto-Healing Arguments.
"""

import json
import os
from pathlib import Path
from typing import Dict, Any, List, Optional, Union
import logging
from datetime import datetime

class MemoryManager:
    """Manages all memory operations for Agent 50."""
    
    def __init__(self):
        """Initialize memory manager with file paths."""
        # Pathlib ka use (DeepSeek Style) - Professional approach
        self.base_path = Path(os.getcwd()) / "agent50_core" / "memory_data"
        self.logger = logging.getLogger("Agent50.Memory")
        
        # Memory file paths
        self.files = {
            "architecture_patterns": self.base_path / "architecture_patterns.json",
            "deployment_failures": self.base_path / "deployment_failures.json",
            "fixes_applied": self.base_path / "fixes_applied.json",
            "project_status": self.base_path / "project_status.json"
        }
        
        # In-memory cache
        self.cache = {}
        
        # Auto-Initialize on Startup
        self.initialize()

    def initialize(self):
        """Initialize memory system - create files if they don't exist."""
        self.logger.info("Initializing memory system...")
        
        # Ensure memory directory exists
        self.base_path.mkdir(parents=True, exist_ok=True)
        
        # Initialize each memory file with default structure
        for file_name, file_path in self.files.items():
            if not file_path.exists():
                self._create_default_file(file_name, file_path)
            
        # Load all memory files into cache
        self._load_all_to_cache()
        self.logger.info("Memory system initialized")

    def _create_default_file(self, file_name: str, file_path: Path):
        """Create a memory file with default structure."""
        defaults = {
            "architecture_patterns": {
                "patterns": [],
                "last_updated": datetime.now().isoformat(),
                "version": "1.0"
            },
            "deployment_failures": {
                "failures": [],
                "failure_count": 0,
                "last_updated": datetime.now().isoformat()
            },
            "fixes_applied": {
                "fixes": [],
                "total_fixes": 0,
                "last_updated": datetime.now().isoformat()
            },
            "project_status": {
                "current_project": None,
                "projects": {},
                "overall_stats": {
                    "total_projects": 0,
                    "successful_deployments": 0,
                    "failed_deployments": 0
                }
            }
        }
        
        default_content = defaults.get(file_name, {})
        with open(file_path, 'w') as f:
            json.dump(default_content, f, indent=2)

    def _load_all_to_cache(self):
        """Load all memory files into cache."""
        for file_name, file_path in self.files.items():
            try:
                with open(file_path, 'r') as f:
                    self.cache[file_name] = json.load(f)
            except (json.JSONDecodeError, FileNotFoundError):
                # Recreate file if corrupt
                self._create_default_file(file_name, file_path)
                with open(file_path, 'r') as f:
                    self.cache[file_name] = json.load(f)

    def _save_to_file(self, file_name: str):
        """Save cached data to file."""
        if file_name in self.cache:
            file_path = self.files[file_name]
            with open(file_path, 'w') as f:
                json.dump(self.cache[file_name], f, indent=2)

    # ==========================================================
    #  DASHBOARD INTEGRATION
    # ==========================================================
    def save_project_structure(self, project_id: str, blueprint: Dict[str, Any]) -> bool:
        """
        Saves the project blueprint generated by the Dashboard.
        This bridges the gap between Console Server and Memory.
        """
        try:
            # 1. Ensure Projects Directory
            projects_dir = self.base_path / "projects"
            projects_dir.mkdir(exist_ok=True)
            
            # 2. Save Blueprint File
            file_path = projects_dir / f"{project_id}.json"
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(blueprint, f, indent=4)
            
            # 3. Register in DeepSeek Memory (project_status)
            project_name = blueprint.get("name", project_id)
            
            # Call update using the dictionary method (compatible call)
            self.update_project_status({
                "status": "initialized",
                "blueprint_path": str(file_path),
                "type": blueprint.get("type", "unknown")
            }, project_name=project_name)

            self.logger.info(f"✅ Project Structure Saved: {project_name}")
            return True
        except Exception as e:
            self.logger.error(f"❌ Failed to save project structure: {e}")
            return False

    # ==========================================================
    #  CORE MEMORY LOGIC (UPDATED FOR STABILITY)
    # ==========================================================

    def add_architecture_pattern(self, pattern: Dict[str, Any]):
        """Add a new architecture pattern to memory."""
        if "architecture_patterns" not in self.cache:
            self.cache["architecture_patterns"] = {"patterns": []}
        
        pattern["added_at"] = datetime.now().isoformat()
        pattern["used_count"] = pattern.get("used_count", 0) + 1
        
        self.cache["architecture_patterns"]["patterns"].append(pattern)
        
        # Keep only last 100 patterns
        if len(self.cache["architecture_patterns"]["patterns"]) > 100:
            self.cache["architecture_patterns"]["patterns"] = \
                self.cache["architecture_patterns"]["patterns"][-100:]
        
        self._save_to_file("architecture_patterns")

    def update_project_status(self, project_id: Union[str, Dict[str, Any]], status: Any = None, **kwargs):
        """
        Update the status of a project.
        
        CRITICAL FIX: This method now handles **kwargs (like platform, error details)
        and supports both Dictionary input (from Architect) and String input (from Monitor).
        """
        if "project_status" not in self.cache:
             self.cache["project_status"] = {"projects": {}, "overall_stats": {}}
        
        # --- LOGIC TO HANDLE DIFFERENT INPUT TYPES ---
        
        # Case 1: First argument is a Dict (Old Architect Style)
        if isinstance(project_id, dict):
            status_data = project_id
            # Try to get name from kwargs or assume it's current
            p_name = kwargs.get('project_name') or self.cache["project_status"].get("current_project")
        
        # Case 2: First argument is a String (New Monitor Style)
        else:
            p_name = project_id
            # If status is just a string (e.g., "healthy"), convert to dict
            if isinstance(status, str):
                status_data = {
                    "status": status,
                    "timestamp": datetime.now().isoformat()
                }
            else:
                status_data = status if status else {}
            
            # Merge extra arguments (like 'platform') into the status data
            # This prevents the 'unexpected keyword argument' crash
            if kwargs:
                status_data.update(kwargs)

        # Fallback if no name found
        if not p_name:
            p_name = "unknown_project"

        # --- CORE UPDATE LOGIC ---
        
        if p_name not in self.cache["project_status"]["projects"]:
            self.cache["project_status"]["projects"][p_name] = {
                "created_at": datetime.now().isoformat(),
                "status_history": []
            }
        
        # Ensure timestamp exists
        if "timestamp" not in status_data:
            status_data["timestamp"] = datetime.now().isoformat()

        # Update Memory
        self.cache["project_status"]["projects"][p_name]["current_status"] = status_data
        self.cache["project_status"]["projects"][p_name]["status_history"].append(status_data)
        
        # Trim history if too long
        if len(self.cache["project_status"]["projects"][p_name]["status_history"]) > 50:
             self.cache["project_status"]["projects"][p_name]["status_history"] = \
                 self.cache["project_status"]["projects"][p_name]["status_history"][-50:]

        self._save_to_file("project_status")

    def get_project_status(self, project_name: Optional[str] = None):
        """Get current status of a project."""
        return self.cache.get("project_status", {})

    def record_deployment_failure(self, project_name, platform, error, logs):
        """Record a deployment failure for analysis."""
        if "deployment_failures" not in self.cache:
            self.cache["deployment_failures"] = {"failures": [], "failure_count": 0}
        
        failure = {
            "project": project_name,
            "platform": platform,
            "error": str(error),
            "timestamp": datetime.now().isoformat()
        }
        
        self.cache["deployment_failures"]["failures"].append(failure)
        self.cache["deployment_failures"]["failure_count"] += 1
        self._save_to_file("deployment_failures")